### ISSUE TITLE
JSON parse error

### ISSUE THREAD

**Issue by ghost** [pandoc-scholar/pandoc-scholar#15]
Getting this error, not sure why:

      $> make
    pandoc --standalone --filter=pandoc-citeproc \
                   --pdf-engine=pdflatex --template=C://Pandoc-scholar/templates/pandoc-scholar.latex \
                   --output article.latex article.enriched.json
    JSON parse error
    make: ** [article.latex] Error 64

**Comment by tarleb** [comment]
Please try to run `make clean` (which will remove all *output.\** files). If the problem persists, then please try upgrading pandoc to version 2.1 or later, as you might have hit a bug in pandoc's custom writer which is present in all 2.0.* releases (my bad, sorry).

**Comment by ghost** [comment]
Still getting the same error I'm afraid. Updated to Pandoc 2.1.1 and did `make clean` as suggested.

**Comment by tarleb** [comment]
Huh, this is weird. I tested with a couple of input files and could not reproduce this. Would it be possible to share the input file? You can mail me directly if posting it online is out of the question.

**Comment by ghost** [comment]
My apologies for taking a while to reply. The input file can be seen [here](https://raw.githubusercontent.com/intgbles/research/master/body.md). 

Tried without the metadata block and got the same result I'm afraid:
![screenshot_1](https://user-images.githubusercontent.com/11869768/35598647-9a03d0b2-061c-11e8-9f95-c4dc4b971ab4.jpg)

Threw a document with only one header and one paragraph and got the exact same output.

Here's my `Makefile`:

```
ARTICLE_FILE        = body.md
OUTFILE_PREFIX      = uwa

DEFAULT_EXTENSIONS = pdf

PANDOC_SCHOLAR_PATH = C://Pandoc-scholar
include $(PANDOC_SCHOLAR_PATH)/Makefile

```

**Comment by tarleb** [comment]
Thanks for the file. It allowed me to identify two bugs in panlunatic, i.e., the package we use to "simulate" Lua filters. I'm not sure if I'll get to fix them, since panlunatic is pretty much deprecated now that pandoc has Lua filters built-in.

To get your file to work with pandoc-scholar, please

- convert the number in the version into a string by wrapping it in quotes `'1.0'`, and
- remove the leading pipe from your abstract or put the abstract into a separate section named *abstract*:

  ```
  # Abstract

  Your abstract goes here.

  ## First header of the document
  ```

I hope to find some time this weekend, so I can move the code from panlunatic to real lua filters.

**Comment by ghost** [comment]
Still getting the same error. It must be me who's doing something wrong because I tried with your example article without success too.

**Comment by tarleb** [comment]
I'm very sorry that it's not working the way it should. 😞 Let's hope that pure Lua filters will fix this.

**Comment by tarleb** [comment]
We are using Lua filters now, so this should no longer be a problem with the upcoming release.
