### ISSUE TITLE
Issues with pandoc > 1.16 on Win 10

### ISSUE THREAD

**Issue by jbin** [pandoc-scholar/pandoc-scholar#21]
There are multiple isuues which I noted using it on Win10 with a pandoc version > 1.16:

If you are using Pandoc 2 then it complains ablout the --smart option (which seems to be removed/replaced)
Using 1.19 I get an error on pancod-citeproc (Permission denied).

Using 1.16 it works.
Unfortunately I am no pandoc/latex expert and could not find a solution to this.
Maybe it should at least be noted, that pandoc version should be 1.16

**Comment by tarleb** [comment]
Thanks for the report. The `--smart` issue is fixed in the current development version, but I didn't get around yet to prepare a new release.

I'm not sure about the other problems you describe.  We are not doing anything weird in terms of calling pandoc-citeproc. I'm also unaware of any reports which would indicate that permissions are a known or common problem with pandoc 1.19. I don't have a Windows machine around right now, so I cannot test this right now. Could you try to just re-install pandoc 1.19?

**Comment by tarleb** [comment]
I'm assuming that this has been resolved.
